[project]
name = "py-programming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "build123d>=0.10.0",
    "ocp-vscode>=3.0.1",
]
