[project]
name = "IgnisCAD"
version = "0.1.0"
description = "Nothing here."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "build123d<0.10",
    "ocp-vscode>=3.0.1",
    "yacv-server>=0.9.7",
]
[[tool.uv.index]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
